name: CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
env:
  DOTNET_VERSION: '10.x'

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Execute tests
      run: | 
        dotnet test ./tools/PawnMapTranslator.Tests/PawnMapTranslator.Tests.csproj -c Release
        dotnet test ./src/SampSharp.MapObjects.Tests/SampSharp.MapObjects.Tests.csproj -c Release